name = "JustRelax"
uuid = "34418575-392d-4e26-8c6d-96b0910afa06"
authors = ["Albert De Montserrat <albertdemontserratnavarro@erdw.ethz.ch>, Pascal Aellig <paellig@uni-mainz.de>"]
version = "0.4.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CellArrays = "d35fcfd7-7af4-4c67-b1aa-d78070614af4"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
GeoParams = "e018b62d-d9de-4a26-8697-af89c310ae38"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImplicitGlobalGrid = "4d7a3746-15be-11ea-1130-334b0c4f5fa0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JustPIC = "10dc771f-8528-4cd9-9d3b-b21b2e693339"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
JustRelaxAMDGPUExt = "AMDGPU"
JustRelaxCUDAExt = "CUDA"

[compat]
AMDGPU = "0.8, 0.9, 1"
Adapt = "4"
CUDA = "5"
CellArrays = "0.2, 0.3"
Crayons = "4.1.1"
GeoParams = "0.6.8, 0.7"
HDF5 = "0.17.1"
ImplicitGlobalGrid = "0.15, 0.16"
JLD2 = "0.4, 0.5"
JustPIC = "0.5"
MPI = "0.20"
MuladdMacro = "0.2"
ParallelStencil = "0.13.6, 0.14"
Reexport = "1.2.2"
StaticArrays = "1"
Statistics = "1"
TOML = "1.0.3"
WriteVTK = "1.18, 1.19"
julia = "1.9, 1.10"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
